In [220]:
import pandas as pd
import numpy as np

In [221]:
movies = pd.read_csv(r'C:\Users\jaiad.APPAUMMI\Documents\MOVIE RECOMMENDATION SYSTEM\Dataset\tmdb_5000_movies.csv')
credits = pd.read_csv(r'C:\Users\jaiad.APPAUMMI\Documents\MOVIE RECOMMENDATION SYSTEM\Dataset\tmdb_5000_credits.csv')

In [222]:
movies.shape

(4803, 20)

In [223]:
credits.shape

(4803, 4)

In [224]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bondâ€™s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [225]:
credits.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [226]:
movies = movies.merge(credits, on = 'title')

In [227]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bondâ€™s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,206647,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,49026,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,49529,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [228]:
movies.shape

(4809, 23)

In [229]:
movies = movies[['movie_id','title','keywords','genres','overview','cast','crew']]

In [230]:
movies.head()

,movie_id,title,keywords,genres,overview,cast,crew
0,19995,Avatar,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","In the 22nd century, a paraplegic Marine is di...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","Captain Barbossa, long believed to be dead, ha...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",A cryptic message from Bondâ€™s past sends him o...,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",Following the death of District Attorney Harve...,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","John Carter is a war-weary, former military ca...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [231]:
movies.shape

(4809, 7)

In [232]:
import ast

def change(text):
    l=[]
    for i in ast.literal_eval(text):
        l.append(i['name'])
        
    return l

In [233]:
movies['genres'] = movies['genres'].apply(change)

In [234]:
movies.head()

,movie_id,title,keywords,genres,overview,cast,crew
0,19995,Avatar,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[Action, Adventure, Fantasy, Science Fiction]","In the 22nd century, a paraplegic Marine is di...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[Adventure, Fantasy, Action]","Captain Barbossa, long believed to be dead, ha...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[Action, Adventure, Crime]",A cryptic message from Bondâ€™s past sends him o...,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[Action, Crime, Drama, Thriller]",Following the death of District Attorney Harve...,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[Action, Adventure, Science Fiction]","John Carter is a war-weary, former military ca...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [235]:
movies.shape

(4809, 7)

In [236]:
import ast

def context(text):
    l=[]
    for i in ast.literal_eval(text):
        l.append(i['name'])
        
    return l

In [237]:
movies['keywords'] = movies['keywords'].apply(context)

In [238]:
movies.head()

,movie_id,title,keywords,genres,overview,cast,crew
0,19995,Avatar,"[culture clash, future, space war, space colon...","[Action, Adventure, Fantasy, Science Fiction]","In the 22nd century, a paraplegic Marine is di...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[ocean, drug abuse, exotic island, east india ...","[Adventure, Fantasy, Action]","Captain Barbossa, long believed to be dead, ha...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[spy, based on novel, secret agent, sequel, mi...","[Action, Adventure, Crime]",A cryptic message from Bondâ€™s past sends him o...,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[dc comics, crime fighter, terrorist, secret i...","[Action, Crime, Drama, Thriller]",Following the death of District Attorney Harve...,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[based on novel, mars, medallion, space travel...","[Action, Adventure, Science Fiction]","John Carter is a war-weary, former military ca...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [239]:
movies.shape

(4809, 7)

In [240]:
import ast

def value(text):
    l=[]
    counter = 0
    for i in ast.literal_eval(text):
        if counter<3:
            l.append(i['name'])
        counter+=1
        
    return l

In [241]:
movies['cast'] = movies['cast'].apply(value)

In [242]:
movies.head()

,movie_id,title,keywords,genres,overview,cast,crew
0,19995,Avatar,"[culture clash, future, space war, space colon...","[Action, Adventure, Fantasy, Science Fiction]","In the 22nd century, a paraplegic Marine is di...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[ocean, drug abuse, exotic island, east india ...","[Adventure, Fantasy, Action]","Captain Barbossa, long believed to be dead, ha...","[Johnny Depp, Orlando Bloom, Keira Knightley]","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[spy, based on novel, secret agent, sequel, mi...","[Action, Adventure, Crime]",A cryptic message from Bondâ€™s past sends him o...,"[Daniel Craig, Christoph Waltz, LÃ©a Seydoux]","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[dc comics, crime fighter, terrorist, secret i...","[Action, Crime, Drama, Thriller]",Following the death of District Attorney Harve...,"[Christian Bale, Michael Caine, Gary Oldman]","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[based on novel, mars, medallion, space travel...","[Action, Adventure, Science Fiction]","John Carter is a war-weary, former military ca...","[Taylor Kitsch, Lynn Collins, Samantha Morton]","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [243]:
import ast

def kind(text):
    l=[]
    for i in ast.literal_eval(text):
        l.append(i['name'])
        
    return l

In [244]:
movies['crew'] = movies['crew'].apply(kind)

In [245]:
movies.head()

,movie_id,title,keywords,genres,overview,cast,crew
0,19995,Avatar,"[culture clash, future, space war, space colon...","[Action, Adventure, Fantasy, Science Fiction]","In the 22nd century, a paraplegic Marine is di...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[Stephen E. Rivkin, Rick Carter, Christopher B..."
1,285,Pirates of the Caribbean: At World's End,"[ocean, drug abuse, exotic island, east india ...","[Adventure, Fantasy, Action]","Captain Barbossa, long believed to be dead, ha...","[Johnny Depp, Orlando Bloom, Keira Knightley]","[Dariusz Wolski, Gore Verbinski, Jerry Bruckhe..."
2,206647,Spectre,"[spy, based on novel, secret agent, sequel, mi...","[Action, Adventure, Crime]",A cryptic message from Bondâ€™s past sends him o...,"[Daniel Craig, Christoph Waltz, LÃ©a Seydoux]","[Thomas Newman, Sam Mendes, Anna Pinnock, John..."
3,49026,The Dark Knight Rises,"[dc comics, crime fighter, terrorist, secret i...","[Action, Crime, Drama, Thriller]",Following the death of District Attorney Harve...,"[Christian Bale, Michael Caine, Gary Oldman]","[Hans Zimmer, Charles Roven, Christopher Nolan..."
4,49529,John Carter,"[based on novel, mars, medallion, space travel...","[Action, Adventure, Science Fiction]","John Carter is a war-weary, former military ca...","[Taylor Kitsch, Lynn Collins, Samantha Morton]","[Andrew Stanton, Andrew Stanton, John Lasseter..."

In [246]:
movies.isnull().sum()

movie_id    0
title       0
keywords    0
genres      0
overview    3
cast        0
crew        0
dtype: int64

In [247]:
movies.dropna(inplace=True)

In [248]:
movies.isnull().sum()

movie_id    0
title       0
keywords    0
genres      0
overview    0
cast        0
crew        0
dtype: int64

In [249]:
movies['overview'] = movies['overview'].apply(lambda x:x.split())

In [250]:
movies.head()

,movie_id,title,keywords,genres,overview,cast,crew
0,19995,Avatar,"[culture clash, future, space war, space colon...","[Action, Adventure, Fantasy, Science Fiction]","[In, the, 22nd, century,, a, paraplegic, Marin...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[Stephen E. Rivkin, Rick Carter, Christopher B..."
1,285,Pirates of the Caribbean: At World's End,"[ocean, drug abuse, exotic island, east india ...","[Adventure, Fantasy, Action]","[Captain, Barbossa,, long, believed, to, be, d...","[Johnny Depp, Orlando Bloom, Keira Knightley]","[Dariusz Wolski, Gore Verbinski, Jerry Bruckhe..."
2,206647,Spectre,"[spy, based on novel, secret agent, sequel, mi...","[Action, Adventure, Crime]","[A, cryptic, message, from, Bondâ€™s, past, send...","[Daniel Craig, Christoph Waltz, LÃ©a Seydoux]","[Thomas Newman, Sam Mendes, Anna Pinnock, John..."
3,49026,The Dark Knight Rises,"[dc comics, crime fighter, terrorist, secret i...","[Action, Crime, Drama, Thriller]","[Following, the, death, of, District, Attorney...","[Christian Bale, Michael Caine, Gary Oldman]","[Hans Zimmer, Charles Roven, Christopher Nolan..."
4,49529,John Carter,"[based on novel, mars, medallion, space travel...","[Action, Adventure, Science Fiction]","[John, Carter, is, a, war-weary,, former, mili...","[Taylor Kitsch, Lynn Collins, Samantha Morton]","[Andrew Stanton, Andrew Stanton, John Lasseter..."

In [251]:
def remove(word):
    l=[]
    for i in word:
        l.append(i.replace(" ", ""))
                
    return l

In [252]:
movies['cast'] = movies['cast'].apply(remove)
movies['keywords'] = movies['keywords'].apply(remove)
movies['genres'] = movies['genres'].apply(remove)
movies['crew'] = movies['crew'].apply(remove)

In [253]:
movies.head()

,movie_id,title,keywords,genres,overview,cast,crew
0,19995,Avatar,"[cultureclash, future, spacewar, spacecolony, ...","[Action, Adventure, Fantasy, ScienceFiction]","[In, the, 22nd, century,, a, paraplegic, Marin...","[SamWorthington, ZoeSaldana, SigourneyWeaver]","[StephenE.Rivkin, RickCarter, ChristopherBoyes..."
1,285,Pirates of the Caribbean: At World's End,"[ocean, drugabuse, exoticisland, eastindiatrad...","[Adventure, Fantasy, Action]","[Captain, Barbossa,, long, believed, to, be, d...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]","[DariuszWolski, GoreVerbinski, JerryBruckheime..."
2,206647,Spectre,"[spy, basedonnovel, secretagent, sequel, mi6, ...","[Action, Adventure, Crime]","[A, cryptic, message, from, Bondâ€™s, past, send...","[DanielCraig, ChristophWaltz, LÃ©aSeydoux]","[ThomasNewman, SamMendes, AnnaPinnock, JohnLog..."
3,49026,The Dark Knight Rises,"[dccomics, crimefighter, terrorist, secretiden...","[Action, Crime, Drama, Thriller]","[Following, the, death, of, District, Attorney...","[ChristianBale, MichaelCaine, GaryOldman]","[HansZimmer, CharlesRoven, ChristopherNolan, C..."
4,49529,John Carter,"[basedonnovel, mars, medallion, spacetravel, p...","[Action, Adventure, ScienceFiction]","[John, Carter, is, a, war-weary,, former, mili...","[TaylorKitsch, LynnCollins, SamanthaMorton]","[AndrewStanton, AndrewStanton, JohnLasseter, C..."

In [254]:
movies['tags'] = movies['overview'] + movies['genres'] + movies['keywords'] + movies['cast'] + movies['crew']

In [255]:
movies.head()

,movie_id,title,keywords,genres,overview,cast,crew,tags
0,19995,Avatar,"[cultureclash, future, spacewar, spacecolony, ...","[Action, Adventure, Fantasy, ScienceFiction]","[In, the, 22nd, century,, a, paraplegic, Marin...","[SamWorthington, ZoeSaldana, SigourneyWeaver]","[StephenE.Rivkin, RickCarter, ChristopherBoyes...","[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[ocean, drugabuse, exoticisland, eastindiatrad...","[Adventure, Fantasy, Action]","[Captain, Barbossa,, long, believed, to, be, d...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]","[DariuszWolski, GoreVerbinski, JerryBruckheime...","[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[spy, basedonnovel, secretagent, sequel, mi6, ...","[Action, Adventure, Crime]","[A, cryptic, message, from, Bondâ€™s, past, send...","[DanielCraig, ChristophWaltz, LÃ©aSeydoux]","[ThomasNewman, SamMendes, AnnaPinnock, JohnLog...","[A, cryptic, message, from, Bondâ€™s, past, send..."
3,49026,The Dark Knight Rises,"[dccomics, crimefighter, terrorist, secretiden...","[Action, Crime, Drama, Thriller]","[Following, the, death, of, District, Attorney...","[ChristianBale, MichaelCaine, GaryOldman]","[HansZimmer, CharlesRoven, ChristopherNolan, C...","[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[basedonnovel, mars, medallion, spacetravel, p...","[Action, Adventure, ScienceFiction]","[John, Carter, is, a, war-weary,, former, mili...","[TaylorKitsch, LynnCollins, SamanthaMorton]","[AndrewStanton, AndrewStanton, JohnLasseter, C...","[John, Carter, is, a, war-weary,, former, mili..."

In [256]:
movies.iloc[0]['tags']

['In',
 'the',
 '22nd',
 'century,',
 'a',
 'paraplegic',
 'Marine',
 'is',
 'dispatched',
 'to',
 'the',
 'moon',
 'Pandora',
 'on',
 'a',
 'unique',
 'mission,',
 'but',
 'becomes',
 'torn',
 'between',
 'following',
 'orders',
 'and',
 'protecting',
 'an',
 'alien',
 'civilization.',
 'Action',
 'Adventure',
 'Fantasy',
 'ScienceFiction',
 'cultureclash',
 'future',
 'spacewar',
 'spacecolony',
 'society',
 'spacetravel',
 'futuristic',
 'romance',
 'space',
 'alien',
 'tribe',
 'alienplanet',
 'cgi',
 'marine',
 'soldier',
 'battle',
 'loveaffair',
 'antiwar',
 'powerrelations',
 'mindandsoul',
 '3d',
 'SamWorthington',
 'ZoeSaldana',
 'SigourneyWeaver',
 'StephenE.Rivkin',
 'RickCarter',
 'ChristopherBoyes',
 'ChristopherBoyes',
 'MaliFinn',
 'JamesHorner',
 'JamesCameron',
 'JamesCameron',
 'JamesCameron',
 'JamesCameron',
 'JamesCameron',
 'AndrewMenzies',
 'JillBrooks',
 'MargerySimkin',
 'KevinIshioka',
 'DickBernstein',
 'ShannonMills',
 'DennieThorpe',
 'JanaVance',
 'DeborahLynnScott',
 'JonLandau',
 'SeanHaworth',
 'KimSinclair',
 'KimSinclair',
 'RichardF.Mays',
 'LaetaKalogridis',
 'MayesC.Rubeo',
 'MauroFiore',
 'ScottHerbertson',
 'WoodySchultz',
 'LindaDeVetta',
 'LindaDeVetta',
 'RichardBluck',
 'SimonBright',
 'RichardMartin',
 'SteveR.Moore',
 'JohnRefoua',
 'KarlJ.Martin',
 'ChilingLin',
 'IlramChoi',
 'StevenQuale',
 'CarlaMeyer',
 'NickBassett',
 'JillCormack',
 'AndyMcLaren',
 'TerryNotary',
 'GarrettWarren',
 'JonathanRothbart',
 'StefanDechant',
 'ToddCherniawsky',
 'MirandaRivers',
 'RobertStromberg',
 'JohnHarding',
 'RobertoDeAngelis',
 'MikeSmithson',
 'AlainLalanne',
 'LucasSalton',
 'JanaceTashjian',
 'StephenRosenbaum',
 'FrankieKarena',
 'LisaLovaas',
 'JonathanFawkner',
 'RobertBavin',
 'AnthonyAlmaraz',
 'CarolynM.Fenton',
 'BethKoenigsberg',
 'SamPage',
 'TexKadonaga',
 'KimFoscato',
 'TammyS.Lee',
 'DennyCaira',
 'JamesWaitkus',
 'AddisonTeague',
 'C.ScottBaker',
 'LukeCaska',
 'DavidChow',
 'JonathanDyer',
 'JosephHiura',
 'RebeccaJellie',
 'RobertAndrewJohnson',
 'MikeStassi',
 'JohnVillarino',
 'JeffreyWisniewski',
 'CherylNardi',
 'MarshallWinn',
 'GwendolynYatesWhittle',
 'WilliamStein',
 'LulaWashington',
 'ChrisDelConte',
 'R.ChristopherWhite',
 'DanLemmon',
 'TimNielsen',
 'MichaelMulholland',
 'ThomasNittmann',
 'EdsonWilliams',
 'ChristineCarr',
 'JohnBruno',
 'DavidEmmerichs',
 'ChristopherScarabosio',
 'JenniferTeves',
 'BrigitteYorke',
 'KenFischer',
 'IainHutton',
 'SteveIngram',
 'JoyceCox',
 'JennyFoster',
 'ChristopherMarino',
 'JimMilton',
 'CyndiOchs',
 'LucasPutnam',
 "Anthony'Max'Ivins",
 'JohnKnoll',
 'EricSaindon',
 'WayneStables',
 'DavidStinnett',
 'GuyWilliams',
 'StuartThorp',
 'GilesCoburn',
 'MarkFellman',
 'ScottSprague',
 'JeremyHollobon',
 'OrlandoMeunier',
 'TaisukeTanimura',
 'LiliaMishelAcevedo',
 'AlejandroM.Hernandez',
 'MarvinHall',
 'JudyAlley',
 'MikePerry',
 'AndrewMorley',
 'SethEngstrom',
 'EricOliver',
 'MatsuneSuzuki',
 'PaulTobin',
 'RoxaneGriffin',
 'ArunRam-Mohan',
 'GeorgiaLockhart-Adams',
 'ThrainShadbolt',
 'BradAlexander',
 'ShadiAlmassizadeh',
 'SimonClutterbuck',
 'GraemeDemmocks',
 'AdrianFernandes',
 'MitchGates',
 'JerryKung',
 'AndyLomas',
 'SebastianMarino',
 'MatthiasMenz',
 'SergeiNevshupov',
 'PhilippeRebours',
 'MichaelTakarangi',
 'DavidWeitzberg',
 'BenWhite',
 'MinWindle']

In [257]:
newdf = movies[['movie_id','title','tags']]

In [258]:
newdf.head()

,movie_id,title,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."

In [259]:
newdf['tags'] = newdf['tags'].apply(lambda x: " ".join(x))

C:\Users\jaiad.APPAUMMI\AppData\Local\Temp\ipykernel_19408\2433798782.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  newdf['tags'] = newdf['tags'].apply(lambda x: " ".join(x))

In [260]:
newdf.head()

,movie_id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."

In [261]:
import nltk
from nltk import PorterStemmer

In [262]:
ps = PorterStemmer()

In [263]:
def stems(text):
    l=[]
    for i in text.split():
        l.append(ps.stem(i))
        
        
    return " ".join(l)

In [264]:
newdf['tags'] = newdf['tags'].apply(stems)

C:\Users\jaiad.APPAUMMI\AppData\Local\Temp\ipykernel_19408\2911367822.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  newdf['tags'] = newdf['tags'].apply(stems)

In [265]:
newdf.iloc[0]['tags']

"in the 22nd century, a parapleg marin is dispatch to the moon pandora on a uniqu mission, but becom torn between follow order and protect an alien civilization. action adventur fantasi sciencefict cultureclash futur spacewar spacecoloni societi spacetravel futurist romanc space alien tribe alienplanet cgi marin soldier battl loveaffair antiwar powerrel mindandsoul 3d samworthington zoesaldana sigourneyweav stephene.rivkin rickcart christopherboy christopherboy malifinn jameshorn jamescameron jamescameron jamescameron jamescameron jamescameron andrewmenzi jillbrook margerysimkin kevinishioka dickbernstein shannonmil denniethorp janav deborahlynnscott jonlandau seanhaworth kimsinclair kimsinclair richardf.may laetakalogridi mayesc.rubeo maurofior scottherbertson woodyschultz lindadevetta lindadevetta richardbluck simonbright richardmartin stever.moor johnrefoua karlj.martin chilinglin ilramchoi stevenqual carlamey nickbassett jillcormack andymclaren terrynotari garrettwarren jonathanrothbart stefandech toddcherniawski mirandariv robertstromberg johnhard robertodeang mikesmithson alainlalann lucassalton janacetashjian stephenrosenbaum frankiekarena lisalovaa jonathanfawkn robertbavin anthonyalmaraz carolynm.fenton bethkoenigsberg sampag texkadonaga kimfoscato tammys.le dennycaira jameswaitku addisonteagu c.scottbak lukecaska davidchow jonathandy josephhiura rebeccajelli robertandrewjohnson mikestassi johnvillarino jeffreywisniewski cherylnardi marshallwinn gwendolynyateswhittl williamstein lulawashington chrisdelcont r.christopherwhit danlemmon timnielsen michaelmulholland thomasnittmann edsonwilliam christinecarr johnbruno davidemmerich christopherscarabosio jennifertev brigitteyork kenfisch iainhutton steveingram joycecox jennyfost christophermarino jimmilton cyndioch lucasputnam anthony'max'ivin johnknol ericsaindon waynest davidstinnett guywilliam stuartthorp gilescoburn markfellman scottspragu jeremyhollobon orlandomeuni taisuketanimura liliamishelacevedo alejandrom.hernandez marvinhal judyalley mikeperri andrewmorley sethengstrom ericoliv matsunesuzuki paultobin roxanegriffin arunram-mohan georgialockhart-adam thrainshadbolt bradalexand shadialmassizadeh simonclutterbuck graemedemmock adrianfernand mitchgat jerrykung andyloma sebastianmarino matthiasmenz sergeinevshupov philipperebour michaeltakarangi davidweitzberg benwhit minwindl"

In [266]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000, stop_words='english')

In [267]:
vector = cv.fit_transform(newdf['tags']).toarray()

In [268]:
vector

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [269]:
vector.shape

(4806, 5000)

In [270]:
cv.vocabulary_ #gives the no of words in each sentence

{'century': 733,
 'marin': 2902,
 'dispatch': 1285,
 'moon': 3163,
 'uniqu': 4727,
 'mission': 3133,
 'becom': 437,
 'torn': 4631,
 'follow': 1653,
 'order': 3339,
 'protect': 3628,
 'alien': 149,
 'action': 56,
 'adventur': 84,
 'fantasi': 1588,
 'sciencefict': 4034,
 'cultureclash': 1033,
 'futur': 1732,
 'societi': 4227,
 'spacetravel': 4254,
 'futurist': 1734,
 'romanc': 3924,
 'space': 4249,
 'tribe': 4672,
 'soldier': 4232,
 'battl': 421,
 '3d': 26,
 'zoesaldana': 4994,
 'sigourneyweav': 4172,
 'stephene': 4312,
 'rivkin': 3852,
 'rickcart': 3832,
 'christopherboy': 820,
 'malifinn': 2866,
 'jameshorn': 2223,
 'jamescameron': 2213,
 'andrewmenzi': 213,
 'margerysimkin': 2895,
 'kevinishioka': 2576,
 'dickbernstein': 1254,
 'shannonmil': 4132,
 'denniethorp': 1210,
 'janav': 2247,
 'deborahlynnscott': 1177,
 'seanhaworth': 4067,
 'richardf': 3810,
 'maurofior': 2998,
 'moor': 3164,
 'martin': 2954,
 'toddcherniawski': 4599,
 'lisalovaa': 2763,
 'le': 2696,
 'dennycaira': 1216,
 'cherylnardi': 770,
 'marshallwinn': 2951,
 'gwendolynyateswhittl': 1905,
 'edsonwilliam': 1406,
 'johnbruno': 2387,
 'davidemmerich': 1109,
 'christopherscarabosio': 830,
 'kenfisch': 2562,
 'max': 2999,
 'guywilliam': 1904,
 'matsunesuzuki': 2982,
 'arunram': 320,
 'mohan': 3150,
 'adam': 62,
 'captain': 674,
 'long': 2788,
 'believ': 447,
 'dead': 1160,
 'ha': 1907,
 'come': 904,
 'life': 2743,
 'head': 1956,
 'edg': 1399,
 'earth': 1391,
 'turner': 4692,
 'elizabeth': 1431,
 'noth': 3294,
 'quit': 3657,
 'ocean': 3313,
 'exoticisland': 1552,
 'loveofone': 2818,
 'slif': 4213,
 'traitor': 4654,
 'shipwreck': 4156,
 'ship': 4155,
 'allianc': 160,
 'afterlif': 94,
 'fighter': 1624,
 'pirat': 3525,
 'aftercreditssting': 93,
 'johnnydepp': 2427,
 'keiraknightley': 2556,
 'dariuszwolski': 1082,
 'jerrybruckheim': 2333,
 'tedelliott': 4500,
 'terryrossio': 4524,
 'hanszimm': 1925,
 'mikestenson': 3109,
 'ericmcleod': 1497,
 'chadoman': 735,
 'denisechamian': 1208,
 'priscillajohn': 3604,
 'pennyros': 3444,
 'bobbadami': 531,
 'veneil': 4762,
 'dottiestarl': 1320,
 'allenhal': 158,
 'sharronreynold': 4139,
 'karengolden': 2530,
 'messag': 3024,
 'bond': 544,
 'past': 3395,
 'send': 4097,
 'trail': 4651,
 'uncov': 4711,
 'sinist': 4191,
 'polit': 3551,
 'forc': 1660,
 'secret': 4075,
 'servic': 4113,
 'alive': 154,
 'deceit': 1184,
 'reveal': 3790,
 'terribl': 4516,
 'truth': 4687,
 'crime': 1012,
 'spi': 4268,
 'basedonnovel': 408,
 'secretag': 4076,
 'sequel': 4104,
 'britishsecretservic': 599,
 'danielcraig': 1059,
 'thomasnewman': 4555,
 'annapinnock': 242,
 'johnlogan': 2418,
 'ianflem': 2082,
 'leesmith': 2708,
 'billbernstein': 483,
 'janytemim': 2262,
 'debbiemcwilliam': 1173,
 'barbarabroccoli': 386,
 'christopherassel': 819,
 'perhallberg': 3450,
 'michaelg': 3053,
 'wilson': 4919,
 'campbel': 665,
 'donaldmowat': 1309,
 'dano': 1075,
 'connel': 939,
 'greggrudloff': 1865,
 'jayne': 2287,
 'anntenggren': 256,
 'scottmillan': 4047,
 'johnt': 2445,
 'cucci': 1029,
 'julianmorson': 2506,
 'annscibelli': 255,
 'jasinboland': 2266,
 'hansbjerno': 1924,
 'alexrous': 141,
 'michellepaz': 3090,
 'karenbakerland': 2529,
 'peterstaubl': 3492,
 'johnmarzano': 2421,
 'adamdal': 63,
 'lucamarcoparacel': 2828,
 'eddiemurphi': 1398,
 'death': 1171,
 'district': 1287,
 'attorney': 345,
 'harvey': 1944,
 'batman': 420,
 'assum': 332,
 'respons': 3777,
 'late': 2672,
 'reput': 3768,
 'hunt': 2074,
 'gotham': 1833,
 'citi': 845,
 'polic': 3545,
 'year': 4974,
 'later': 2673,
 'encount': 1465,
 'mysteri': 3208,
 'kyle': 2644,
 'villain': 4792,
 'new': 3259,
 'terrorist': 4520,
 'leader': 2698,
 'overwhelm': 3358,
 'dark': 1083,
 'knight': 2626,
 'brand': 568,
 'enemy': 1469,
 'drama': 1339,
 'thriller': 4567,
 'dccomic': 1158,
 'crimefight': 1013,
 'secretident': 4078,
 'vigilant': 4789,
 'cover': 990,
 'superhero': 4427,
 'terror': 4519,
 'destruct': 1236,
 'imax': 2103,
 'flood': 1645,
 'christianbal': 809,
 'michaelcain': 3043,
 'garyoldman': 1767,
 'charlesroven': 755,
 'christophernolan': 826,
 'emmathoma': 1458,
 'wallypfist': 4823,
 'johnpapsidera': 2432,
 'davids': 1143,
 'goy': 1837,
 'bobkan': 535,
 'michaeluslan': 3086,
 'lindyhem': 2755,
 'nathancrowley': 3227,
 'kevinkavanaugh': 2580,
 'naamanmarshal': 3212,
 'brian': 576,
 'kizer': 2620,
 'thomastul': 4557,
 'kevinkaska': 2579,
 'kevindelanoy': 2573,
 'garyrizzo': 1768,
 'dougcoleman': 1326,
 'barbaraharri': 387,
 'brucefowl': 621,
 'anderson': 193,
 'deanwolcott': 1170,
 'hugoweng': 2064,
 'johnroesch': 2435,
 'lindamatthew': 2753,
 'richardk': 3816,
 'watkin': 4847,
 'fish': 1636,
 'scottsakamoto': 4051,
 'michaelw': 3087,
 'mitchel': 3142,
 'johnson': 2443,
 'alysondeemoor': 169,
 'dunn': 1370,
 'janicealexand': 2256,
 'deenaadair': 1192,
 'robertw': 3894,
 'joseph': 2473,
 'michaelbabcock': 3037,
 'pack': 3364,
 'paulj': 3423,
 'franklin': 1697,
 'erica': 1491,
 'lewi': 2735,
 'jamesa': 2205,
 'michaelj': 3059,
 'brien': 593,
 'davidorr': 1137,
 'davide': 1107,
 'hal': 1912,
 'sullivan': 4421,
 'john': 2382,
 'carter': 701,
 'war': 4833,
 'militari': 3114,
 'inexplic': 2123,
 'transport': 4657,
 'exot': 1551,
 'planet': 3532,
 'reluctantli': 3752,
 'epic': 1486,
 'conflict': 933,
 'world': 4951,
 'brink': 596,
 'hi': 1986,
 'human': 2065,
 'realiz': 3713,
 'surviv': 4445,
 'peopl': 3446,
 'rest': 3778,
 'hands': 1919,
 'mar': 2881,
 'princess': 3601,
 'escap': 1504,
 '19thcenturi': 20,
 'andrewstanton': 218,
 'johnlasset': 2416,
 'colinwilson': 889,
 'gailsteven': 1741,
 'tomjohnson': 4611,
 'michaelsilv': 3081,
 'juanperalta': 2496,
 'billcorso': 486,
 'michaelgiacchino': 3054,
 'danielmindel': 1063,
 'stephenm': 4320,
 'davi': 1093,
 'johnk': 2414,
 'marciaross': 2887,
 'peterchiang': 3469,
 'dennisliddiard': 1212,
 'joshlusbi': 2486,
 'michaelsemanick': 3079,
 'anniepenn': 251,
 'colinanderson': 886,
 'grubb': 1887,
 'malcolmfif': 2861,
 'andrewm': 210,
 'ward': 4835,
 'karinsilvestri': 2534,
 'seemingli': 4090,
 'spider': 4269,
 'man': 2868,
 'goe': 1820,
 'includ': 2113,
 'shape': 4133,
 'shift': 4154,
 'superpow': 4432,
 'alter': 166,
 'ego': 1419,
 'peter': 3462,
 'parker': 3383,
 'deal': 1163,
 'eddi': 1397,
 'caught': 725,
 'love': 2816,
 'dualident': 1363,
 'amnesia': 185,
 'forgiv': 1670,
 'deathofafriend': 1172,
 'sand': 4002,
 'hostil': 2042,
 'marvelcom': 2961,
 'reveng': 3792,
 'tobeymaguir': 4594,
 'kirstendunst': 2616,
 'jamesfranco': 2218,
 'francinemaisl': 1684,
 'josephm': 2479,
 'caracciolojr': 679,
 'samraimi': 3997,
 'stanle': 4292,
 'aviarad': 358,
 'jamesacheson': 2206,
 'kevinfeig': 2574,
 'billpop': 493,
 'christopheryoung': 834,
 'kathydriscol': 2547,
 'michaelriva': 3077,
 'lesliea': 2721,
 'pop': 3556,
 'stewart': 4367,
 'davidf': 1111,
 'klassen': 2621,
 'dawnswiderski': 1155,
 'merrickmorton': 3022,
 'trudyramirez': 4684,
 'merieweismillerwallac': 3020,
 'lord': 2795,
 'earla': 1387,
 'hibbert': 1987,
 'davidj': 1121,
 'gr': 1838,
 'kingdom': 2612,
 'hide': 1989,
 'taken': 4478,
 'hostag': 2040,
 'beauti': 432,
 'bound': 552,
 'teen': 4502,
 '70': 30,
 'feet': 1611,
 'golden': 1822,
 'hair': 1911,
 'look': 2791,
 'ticket': 4574,
 'lock': 2780,
 'away': 365,
 'years': 4975,
 'strike': 4387,
 'handsom': 1920,
 'thief': 4541,
 'unlik': 4734,
 'duo': 1371,
 'set': 4114,
 'complet': 924,
 'super': 4426,
 'cop': 965,
 'gang': 1749,
 'anim': 235,
 'famili': 1582,
 'magic': 2849,
 'hors': 2036,
 'fairytal': 1575,
 'music': 3201,
 'duringcreditssting': 1373,
 'alanmenken': 116,
 'deana': 1166,
 'zupanc': 4999,
 'fluhr': 1649,
 'ai': 104,
 'lingle': 2757,
 'jasonw': 2279,
 'jen': 2317,
 'richarde': 3809,
 'robertl': 3882,
 'mil': 3110,
 'petti': 3497,
 'toni': 4622,
 'stark': 4297,
 'tri': 4670,
 'program': 3618,
 'thing': 4544,
 'hero': 1982,
 'ultim': 4705,
 'test': 4527,
 'fate': 1600,
 'hang': 1921,
 'aveng': 357,
 'stop': 4372,
 'plans': 3533,
 'soon': 4241,
 'unexpect': 4720,
 'way': 4849,
 'global': 1814,
 'adventure': 85,
 'basedoncomicbook': 407,
 'vision': 4804,
 'marvelcinematicunivers': 2960,
 'robertdowneyjr': 3868,
 'markruffalo': 2934,
 'dannyelfman': 1072,
 'sarahfinn': 4011,
 'briantyl': 588,
 'richardrobert': 3825,
 'josswhedon': 2488,
 'jeffreyford': 2309,
 'bendavi': 454,
 'jackkirbi': 2189,
 'jonfavreau': 2465,
 'louisd': 2810,
 'esposito': 1509,
 'victoriaalonso': 4779,
 'bjmcdonnel': 509,
 'lorahirschberg': 2793,
 'franke': 1693,
 'euln': 1518,
 'daniels': 1067,
 'jaymaid': 2286,
 'jeremybraben': 2330,
 'chriso': 801,
 'garysumm': 1771,
 'briann': 584,
 'bentley': 461,
 'anthonyrizzo': 272,
 'green': 1859,
 'richardrol': 3826,
 'harri': 1937,
 'begin': 443,
 'discov': 1277,
 'old': 3321,
 'book': 546,
 'mark': 2905,
 'half': 1913,
 'blood': 519,
 'prince': 3600,
 'learn': 2700,
 'witch': 4932,
 'broom': 607,
 'werewolf': 4870,
 'stuartcraig': 4395,
 'davidheyman': 1118,
 'andrewackland': 199,
 'snow': 4224,
 'fionaweir': 1633,
 'jaapbuitendijk': 2182,
 'fear': 1607,
 'god': 1819,
 'lik': 2746,
 'left': 2710,
 'city': 847,
 'modern': 3149,
 'day': 1156,
 'wrestl': 4961,
 'sort': 4243,
 'realli': 3714,
 'threat': 4564,
 'quickli': 3655,
 'mankind': 2876,
 'greater': 1854,
 'danger': 1054,
 'known': 2629,
 'benaffleck': 451,
 'frankmil': 1700,
 'lorakennedi': 2794,
 'patricktatopoulo': 3407,
 'michaelwilkinson': 3088,
 'davidbrenn': 1101,
 'troysizemor': 4682,
 'zacksnyd': 4989,
 'chuckmichael': 839,
 'joednaboldin': 2370,
 'stefansonnenfeld': 4305,
 'cal': 653,
 'michaelkel': 3064,
 'katebisco': 2538,
 'gregorys': 1872,
 'hoop': 2029,
 'farrel': 1594,
 'chrisjenkin': 797,
 'davidb': 1100,
 'nowel': 3298,
 'brianhel': 582,
 'brianaveri': 577,
 'lang': 2656,
 'williamr': 4913,
 'return': 3787,
 'allow': 162,
 'walk': 4821,
 'free': 1712,
 'wa': 4811,
 'abandon': 37,
 'plot': 3538,
 'million': 3117,
 'kill': 2600,
 'chang': 744,
 'face': 1570,
 'forever': 1668,
 'rid': 3836,
 'steel': 4304,
 'savingtheworld': 4020,
 'kevinspacey': 2587,
 'katebosworth': 2539,
 'rogermussenden': 3913,
 'bryansing': 627,
 'johnottman': 2430,
 'newtonthomassigel': 3267,
 'williamfay': 4904,
 'stephenjon': 4318,
 'continu': 954,
 'jame': 2203,
 'casino': 708,
 'betray': 474,
 'woman': 4936,
 'fight': 1623,
 'make': 2857,
 'latest': 2674,
 'pursu': 3644,
 'determin': 1240,
 'interrog': 2152,
 'mr': 3193,
 'white': 4882,
 'organ': 3343,
 'blackmail': 511,
 'far': 1591,
 'complex': 925,
 'anyon': 278,
 'undercov': 4713,
 'paulhaggi': 3419,
 'louisefrogley': 2811,
 'davidarnold': 1098,
 'richardpearson': 3823,
 'jack': 2183,
 'work': 4947,
 'debt': 1181,
 'jones': 2464,
 'attempt': 341,
 'avoid': 360,
 'etern': 1513,
 'monster': 3158,
 'daughter': 1090,
 'camillefriend': 661,
 'texa': 4528,
 'ranger': 3693,
 'chase': 764,
 'outlaw': 3354,
 'led': 2702,
 'ambush': 178,
 'survivor': 4447,
 'american': 180,
 'indian': 2119,
 'nurs': 3304,
 'health': 1958,
 'don': 1304,
 'mask': 2972,
 'ride': 3838,
 'silver': 4175,
 'team': 4494,
 'bring': 595,
 'justice': 2522,
 'western': 4875,
 'partner': 3389,
 'lawyer': 2693,
 'train': 4652,
 'garyrydstrom': 1770,
 'jessgonchor': 2338,
 'anthonydininno': 266,
 'markedwardwright': 2912,
 'leeorloff': 2706,
 'young': 4980,
 'boy': 558,
 'extraordinari': 1564,
 'power': 3571,
 'thi': 4540,
 'journey': 2491,
 'came': 657,
 'sent': 4100,
 'emerg': 1451,
 'save': 4019,
 'symbol': 4474,
 'hope': 2031,
 'superhuman': 4428,
 'alieninvas': 150,
 'amyadam': 188,
 'annekuljian': 246,
 'helenjarvi': 1971,
 'amirmokri': 184,
 'incred': 2115,
 'lion': 2759,
 'luci': 2830,
 'susan': 4448,
 'aid': 105,
 'princ': 3599,
 'threaten': 4565,
 'evil': 1538,
 'king': 2611,
 'help': 1975,
 'color': 900,
 'cast': 709,
 'characters': 749,
 'clan': 852,
 'embark': 1450,
 'quest': 3652,
 'right': 3841,
 'heir': 1967,
 'brothersisterrelationship': 613,
 'faith': 1576,
 'uncl': 4709,
 'fantasyworld': 1590,
 'lizmullan': 2771,
 'markjohnson': 2922,
 'andrewadamson': 200,
 'jon': 2455,
 'hodenfield': 2010,
 'isismussenden': 2172,
 'harrygregson': 1941,
 'william': 4899,
 'karlwalterlindenlaub': 2535,
 'nancybishop': 3214,
 'matthewgray': 2990,
 'davidallday': 1096,
 'jasonknox': 2274,
 'johnston': 2444,
 'gregorylundsgaard': 1870,
 'seanbutton': 4063,
 'jakubdvorak': 2201,
 'enemi': 1467,
 'nick': 3275,
 'director': 1272,
 'intern': 2150,
 'need': 3241,
 'pull': 3639,
 'disaster': 1276,
 'span': 4256,
 'globe': 1815,
 'dare': 1079,
 'recruit': 3725,
 'effort': 1417,
 'newyork': 3268,
 'chrisevan': 792,
 'alansilvestri': 118,
 'seamusmcgarvey': 4060,
 'victorj': 4783,
 'zolfo': 4995,
 'richardl': 3817,
 'teresaeckton': 4512,
 'gabrielberistain': 1736,
 'zakpenn': 4991,
 'randihil': 3689,
 'davejordan': 1092,
 'jannengel': 2257,
 'cross': 1021,
 'danielp': 1065,
 'rosen': 3947,
 'mitchdubin': 3141,
 'zaderosenth': 4990,
 'johns': 2436,
 'moy': 3192,
 'davidm': 1131,
 'billo': 491,
 'jamesbak': 2209,
 'michaelqueen': 3075,
 'mikemarcuzzi': 3104,
 'path': 3397,
 'sure': 4437,
 'ruthless': 3973,
 'artist': 318,
 'use': 4747,
 'youth': 4984,
 'queen': 3649,
 'anne': 244,
 'revenge': 3793,
 'doesn': 1297,
 'know': 2628,
 'sea': 4058,
 'sword': 4469,
 'sail': 3987,
 'duke': 1367,
 'mermaid': 3021,
 'penÃ©lopecruz': 3445,
 'barryh': 398,
 'waldman': 4819,
 'paulmassey': 3424,
 'michaelhertlein': 3057,
 'kerrylynmckissick': 2569,
 'georgewattersii': 1794,
 'petermountain': 3484,
 'davidc': 1103,
 'hugh': 2059,
 'aaronwilliam': 35,
 'agent': 98,
 'smith': 4218,
 'tommi': 4612,
 'lee': 2703,
 'time': 4581,
 'seen': 4091,
 '15': 6,
 'men': 3015,
 'black': 510,
 'stake': 4288,
 'travel': 4661,
 'univers': 4729,
 'told': 4605,
 'themselv': 4536,
 'josh': 2482,
 'comedi': 905,
 'timetravel': 4583,
 'willsmith': 4917,
 'tommyleejon': 4614,
 'joshbrolin': 2483,
 'stevenspielberg': 4358,
 'ellenchenoweth': 1435,
 'walterf': 4827,
 'park': 3382,
 'barrysonnenfeld': 403,
 'lauriemacdonald': 2686,
 'marye': 2965,
 'stevengraham': 4347,
 'donzimmerman': 1316,
 'susanbod': 4449,
 'lukefreeborn': 2836,
 'hugodominguez': 2063,
 'immedi': 2104,
 'event': 1528,
 'defend': 1197,
 'mountain': 3186,
 'treasur': 4662,
 'claim': 850,
 'ruin': 3955,
 'elv': 1448,
 'armi': 301,
 'march': 2886,
 'fuel': 1726,
 'rise': 3847,
 'middle': 3096,
 'fall': 1578,
 'corrupt': 973,
 'tolkien': 4606,
 'dragon': 1338,
 'swordandsorceri': 4470,
 'ianmckellen': 2085,
 'howardshor': 2055,
 'peterjackson': 3478,
 'franwalsh': 1701,
 'philippaboyen': 3500,
 'andrewlesni': 209,
 'victoriaburrow': 4780,
 'johnhubbard': 2410,
 'guillermodeltoro': 1893,
 'davidbrown': 1102,
 'johnsimpson': 2440,
 'jamesh': 2222,
 'mattweav': 2995,
 'anna': 238,
 'outcast': 3352,
 'high': 1990,
 'parent': 3377,
 'leav': 2701,
 'rais': 3676,
 'ben': 450,
 'aunt': 350,
 'like': 2747,
 'figur': 1625,
 'got': 1832,
 'person': 3455,
 'today': 4597,
 'belong': 448,
 'father': 1601,
 'understand': 4716,
 'parents': 3378,
 'disappear': 1274,
 'lead': 2697,
 'dr': 1335,
 'cours': 986,
 'choic': 782,
 'destini': 1234,
 'lossoffath': 2804,
 'emmaston': 1457,
 'johnschwartzman': 2438,
 'pietroscalia': 3522,
 'kymbarrett': 2645,
 'ianfox': 2083,
 'jamesvanderbilt': 2240,
 'davidgiammarco': 1114,
 'alanedwardbel': 115,
 'robinharlan': 3898,
 'wright': 4962,
 'elizabethhimelstein': 1434,
 'roberttroy': 3893,
 'sarahmonat': 4014,
 'davidluckenbach': 1129,
 'williamj': 4909,
 'davidr': 1140,
 'christensen': 807,
 'jimhenrikson': 2356,
 'robin': 3896,
 'happen': 1926,
 'die': 1259,
 'robert': 3862,
 'promis': 3622,
 'identity': 2093,
 'widow': 4884,
 'draw': 1341,
 'town': 4640,
 'sheriff': 4152,
 'russellcrow': 3967,
 'cateblanchett': 715,
 'briangraz': 581,
 'jinajay': 2362,
 'ridleyscott': 3839,
 'johnmathieson': 2422,
 'jantyy': 2260,
 'arthurmax': 315,
 'brianhelgeland': 583,
 'davidapplebi': 1097,
 'success': 4412,
 'gain': 1742,
 'ring': 3844,
 'gold': 1821,
 'wizard': 4933,
 'tobyemmerich': 4596,
 'petermccaffrey': 3481,
 'la': 2646,
 'shock': 4157,
 'orphan': 3346,
 'trade': 4646,
 'exist': 1548,
 'hall': 1914,
 'jordan': 2472,
 'colleg': 895,
 'north': 3293,
 'unawar': 4708,
 'england': 1473,
 'experi': 1555,
 'basedonyoungadultnovel': 415,
 'nicolekidman': 3280,
 'alexandredesplat': 134,
 'chrisweitz': 835,
 'paulweitz': 3435,
 'annev': 249,
 'andynicholson': 225,
 'ruthmyer': 3974,
 'billcarraro': 485,
 'lucybevan': 2834,
 'howardr': 2054,
 'justinhammond': 2524,
 'york': 4979,
 'ambiti': 176,
 'movi': 3189,
 'produc': 3613,
 'hire': 2001,
 'crew': 1011,
 'skull': 4204,
 'island': 2173,
 'kong': 2630,
 'giant': 1802,
 'ape': 282,
 'smitten': 4219,
 'filmmak': 1628,
 'dinosaur': 1269,
 'naomiwatt': 3222,
 'jackblack': 2184,
 'adrienbrodi': 80,
 'jamesnewtonhoward': 2235,
 'danielhubbard': 1060,
 'rose': 3944,
 'tell': 4508,
 'stori': 4374,
 'bobbi': 533,
 'april': 291,
 'board': 526,
 'depart': 1219,
 'upper': 4740,
 'class': 855,
 'passeng': 3393,
 'mother': 3178,
 'fiancÃ©': 1619,
 'drifter': 1347,
 'best': 469,
 'friend': 1717,
 'win': 4920,
 'game': 1747,
 'voyag': 4809,
 '20': 21,
 'panic': 3374,
 'disast': 1275,
 'katewinslet': 2542,
 'leonardodicaprio': 2718,
 'peterlamont': 3479,
 'richarda': 3800,
 'conradbuffiv': 942,
 'russellcarpent': 3966,
 'kaygeorgi': 2552,
 'simoncran': 4178,
 'johnh': 2406,
 'richardquinn': 3824,
 'age': 96,
 'collect': 892,
 'govern': 1834,
 'pass': 3392,
 'act': 55,
 'design': 1227,
 'caus': 726,
 'iron': 2169,
 'america': 179,
 'civilwar': 849,
 'scarlettjohansson': 4025,
 'ronaldr': 3934,
 'reiss': 3737,
 'judiannamakovski': 2500,
 'henningmolfent': 1976,
 'charliewoebcken': 761,
 'deborahlamiadenav': 1176,
 'jameswhitak': 2243,
 'allana': 155,
 'apon': 285,
 'henryjackman': 1980,
 'gregberri': 1862,
 'wendym': 4867,
 'craig': 995,
 'winth': 4928,
 'mauricek': 2997,
 'mcguir': 3001,
 'radio': 3669,
 'form': 1671,
 'sever': 4120,
 'water': 4846,
 'hawaii': 1954,
 'alex': 130,
 'weapon': 4854,
 'offic': 3317,
 'assign': 329,
 'paul': 3409,
 'engag': 1471,
 'strength': 4384,
 'live': 2767,
 'potenti': 3567,
 'brother': 610,
 'admir': 74,
 'expect': 1553,
 'navi': 3234,
 'soccer': 4225,
 'scientist': 4035,
 'paulrubel': 3427,
 'jeffdawn': 2303,
 'williamladdskinn': 4911,
 'louisemingenbach': 2812,
 'jimpasson': 2359,
 'stevejablonski': 4335,
 'scottstub': 4053,
 'larrydia': 2664,
 'peterberg': 3464,
 'brown': 615,
 'erniemalik': 1499,
 'murphi': 3198,
 'beaubord': 430,
 'frankmasi': 1699,
 'franka': 1690,
 'montaÃ±o': 3161,
 'peteromano': 3485,
 'chrishaarhoff': 793,
 'roberta': 3863,
 'edwardj': 1412,
 'roberte': 3870,
 'evan': 1524,
 'duanemanwil': 1364,
 ...}

In [271]:
from sklearn.metrics.pairwise import cosine_similarity

In [272]:
sim = cosine_similarity(vector)

In [273]:
sim

array([[1.        , 0.07071068, 0.03441236, ..., 0.02948839, 0.        ,
        0.        ],
       [0.07071068, 1.        , 0.03244428, ..., 0.02085144, 0.        ,
        0.02357023],
       [0.03441236, 0.03244428, 1.        , ..., 0.01691275, 0.        ,
        0.        ],
       ...,
       [0.02948839, 0.02085144, 0.01691275, ..., 1.        , 0.04605313,
        0.04914732],
       [0.        , 0.        , 0.        , ..., 0.04605313, 1.        ,
        0.10411584],
       [0.        , 0.02357023, 0.        , ..., 0.04914732, 0.10411584,
        1.        ]])

In [274]:
sim.shape

(4806, 4806)

In [275]:
newdf[newdf['title'] == 'Spider-Man'].index[0]

159

In [276]:
newdf.head(160) #reference

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a parapleg marin is dispa..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believ to be dead, ha c..."
2,206647,Spectre,a cryptic messag from bondâ€™ past send him on a...
3,49026,The Dark Knight Rises,follow the death of district attorney harvey d...
4,49529,John Carter,"john carter is a war-weary, former militari ca..."
...,...,...,...
155,7552,Fun with Dick and Jane,after dick harper lose hi job at globodyn in a...
156,616,The Last Samurai,nathan algren is an american hire to instruct ...
157,147441,Exodus: Gods and Kings,the defiant leader mose rise up against the eg...
158,13475,Star Trek,the fate of the galaxi rest in the hand of bit...
159,557,Spider-Man,"after be bitten by a genet alter spider, nerdi..."

In [277]:
def recommend(movie):
    index = newdf[newdf['title'] == movie].index[0]
    distances = sorted(list(enumerate(sim[index])), reverse= True, key = lambda x:x[1])
    for i in distances[1:10]:
        print(newdf.iloc[i[0]].title)

In [278]:
recommend('Avatar') #in dataframe

Aliens
Titanic
Terminator 2: Judgment Day
True Lies
Titan A.E.
The Abyss
Falcon Rising
Guardians of the Galaxy
The Terminator

In [279]:
recommend('Harry Potter') #not in dataframe

IndexError: index 0 is out of bounds for axis 0 with size 0

In [283]:
import pickle
import os

os.makedirs('Fosters', exist_ok=True)

pickle.dump(newdf, open(r'C:\Users\jaiad.APPAUMMI\Documents\MOVIE RECOMMENDATION SYSTEM\Fosters\MOVIES_LISTS.pkl', 'wb'))
pickle.dump(sim, open(r'C:\Users\jaiad.APPAUMMI\Documents\MOVIE RECOMMENDATION SYSTEM\Fosters\SIMS_VALUES.pkl', 'wb'))